### ISSUE TITLE
Please rename 0.3.3 files to 0.3.4

### ISSUE THREAD

**Issue by purplefox** [sockjs/sockjs-protocol#84]
The 0.3.3 protocol files (e.g. https://github.com/sockjs/sockjs-protocol/blob/master/sockjs-protocol-0.3.3.py) in master have been changed since 0.3.3 was released.

Please can you rename the 0.3.3 files in master so users do not come to your site thinking those are the correct files in master? (The correct ones are in the 0.3.3 tag).

Protocol versioning should be set in stone.

**Comment by purplefox** [comment]
Hi folks. Any update on this?

Cheers :)

**Comment by brycekahle** [comment]
I'll try to get to this sometime during this week. I just recently switched jobs and moved across the country, so my free time a little restricted right now. I'd be happy to review a PR if you are motivated to open one.

**Comment by brycekahle** [comment]
Renamed to `sockjs-protocol` now
