### ISSUE TITLE
which websocket module

### ISSUE THREAD

**Issue by timcoote** [sockjs/sockjs-protocol#86]
When I run the sockjs-protocol-0.3.3.py tests, one (!) of the errors that I get is:
ERROR: test_broken_json (__main__.WebsocketHixie76)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sockjs-protocol-0.3.3.py", line 638, in test_broken_json
    with self.assertRaises(websocket.ConnectionClosedException):
AttributeError: 'module' object has no attribute 'ConnectionClosedException'

The package that I installed with pip was: websocket-client (0.32.0), which has an exception called:
WebSocketConnectionClosedException

Have I installed the wrong package, or is the wrong exception being referenced in sockjs-protocol-0.3.3.py?

**Comment by brycekahle** [comment]
If you look at the `requirements.txt` it uses version `0.4.1`, so yes you used the wrong version.

**Comment by timcoote** [comment]
ok. thanks. when installing with make, I was not getting that 0.4.1 as, requirements_dev.txt was being used.

That's a really old version of websocket-client. As is the ws4py module. Neither of these supports ipv6. Are you interested in a patch to move to newer versions of these modules and hence support ipv6?

Also. Am I correct in thinking that the sockjst-protocol-0.3.3.py ought to work against the sockjs test server (test_server/server.js, in https://github.com/sockjs/sockjs-node ?)  It's close, but not quite.

**Comment by brycekahle** [comment]
Supporting IPv6 would require a new version of the protocol most likely. That is why the websocket-client version hasn't changed is because the protocol hasn't changed.

There have been some small changes to the server for security reasons since 0.3.3 that need to be incorporated into a new version of the protocol.

**Comment by timcoote** [comment]
I can see a few issues with parsing addresses, but there are packages to handle that. As noted, websocket-client (python) and ws4py seem good to go at their latest versions, with minor naming changes. I think that there's only one obvious issue on how the client recv's data, and I seemed to get a lot of keepalives in the xhr. None of the protocol changes are ipv6 specific. I wouldn't expect much to need to change on the protocol above that level. But you may be aware of something that I'm not.

I can see the introduction of /**/ in some of the responses - that's the sort of mod that I had to make to the test. It sounds like that's a mandatory change. The only other changes that I noted were too precise a match on returned javascript and a change to the 'scheme' for WebSocket8Client.

If you want the patched, I'm happy to share them. But they will require a review, particularly of the protocol changes. If you don't, that's fine, too.

**Comment by brycekahle** [comment]
I started digging into the protocol tests yesterday. The reason `websocket-client` is so old is to test Hixie/Draft 76 compatibility. `ws4py` can definitely be updated. 

I'm working through the rest of the test failures, but most of them are because of security updates to `sockjs-node`.
