### ISSUE TITLE
List of dependencies not complete on OSX

### ISSUE THREAD

**Issue by rubahness** [sockjs/sockjs-protocol#89]
After running make test_deps, running sockjs-protocol.py against the virtualenv says the following are missing:
unittest2
ws4py
websocket-client

Using Python 2.7.10 on OSX Yosemite 10.10.5

Using the virtualenv's version of pip to install them allows the tests to start

**Comment by brycekahle** [comment]
Thanks. I think actually the command in the documentation is wrong. Those are listed under `requirements.txt`.
