### ISSUE TITLE
RawWebsocket protocol inside Sockjs: binary or text?

### ISSUE THREAD

**Issue by a-reisberg** [sockjs/sockjs-protocol#92]
I'm reading the Raw Websocket section of the `sockjs` protocol. It seems to me that the default format for the `sockjs` server is to send `text` via the raw websocket instead of `binary`. Is that the correct assumption? Could you please confirm?

Thanks!

[http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html](http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html)

**Comment by brycekahle** [comment]
Correct. Binary is not supported at the moment.

**Comment by a-reisberg** [comment]
Great. Thanks!
